BMacmillan/Labs/car_listings/config/routes.rb
Rails.application.routes.draw do
  resources :prospects
  resources :salesmen
  resources :dealerships
  resources :car_infos
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

BMacmillan/Labs/car_listings/app/models/dealership.rb
class Dealership < ApplicationRecord
end

BMacmillan/Labs/car_listings/app/controllers/dealerships_controller.rb
class DealershipsController < ApplicationController
  before_action :set_dealership, only: [:show, :edit, :update, :destroy]

  # GET /dealerships
  # GET /dealerships.json
  def index
    @dealerships = Dealership.all
  end

  # GET /dealerships/1
  # GET /dealerships/1.json
  def show
  end

  # GET /dealerships/new
  def new
    @dealership = Dealership.new
  end

  # GET /dealerships/1/edit
  def edit
  end

  # POST /dealerships
  # POST /dealerships.json
  def create
    @dealership = Dealership.new(dealership_params)

    respond_to do |format|
      if @dealership.save
        format.html { redirect_to @dealership, notice: 'Dealership was successfully created.' }
        format.json { render :show, status: :created, location: @dealership }
      else
        format.html { render :new }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dealerships/1
  # PATCH/PUT /dealerships/1.json
  def update
    respond_to do |format|
      if @dealership.update(dealership_params)
        format.html { redirect_to @dealership, notice: 'Dealership was successfully updated.' }
        format.json { render :show, status: :ok, location: @dealership }
      else
        format.html { render :edit }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealerships/1
  # DELETE /dealerships/1.json
  def destroy
    @dealership.destroy
    respond_to do |format|
      format.html { redirect_to dealerships_url, notice: 'Dealership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealership
      @dealership = Dealership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dealership_params
      params.require(:dealership).permit(:name, :location_address, :location_city, :location_state, :location_zip, :owner)
    end
end

BMacmillan/Labs/car_listings/app/helpers/dealerships_helper.rb
module DealershipsHelper
end

BMacmillan/Labs/car_listings/app/views/dealerships/_form.html.erb
<%= form_for(dealership) do |f| %>
  <% if dealership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dealership.errors.count, "error") %> prohibited this dealership from being saved:</h2>

      <ul>
      <% dealership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :location_address %>
    <%= f.text_field :location_address %>
  </div>

  <div class="field">
    <%= f.label :location_city %>
    <%= f.text_field :location_city %>
  </div>

  <div class="field">
    <%= f.label :location_state %>
    <%= f.text_field :location_state %>
  </div>

  <div class="field">
    <%= f.label :location_zip %>
    <%= f.text_field :location_zip %>
  </div>

  <div class="field">
    <%= f.label :owner %>
    <%= f.text_field :owner %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

BMacmillan/Labs/car_listings/app/views/dealerships/edit.html.erb
<h1>Editing Dealership</h1>

<%= render 'form', dealership: @dealership %>

<%= link_to 'Show', @dealership %> |
<%= link_to 'Back', dealerships_path %>

BMacmillan/Labs/car_listings/app/views/dealerships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dealerships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location address</th>
      <th>Location city</th>
      <th>Location state</th>
      <th>Location zip</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dealerships.each do |dealership| %>
      <tr>
        <td><%= dealership.name %></td>
        <td><%= dealership.location_address %></td>
        <td><%= dealership.location_city %></td>
        <td><%= dealership.location_state %></td>
        <td><%= dealership.location_zip %></td>
        <td><%= dealership.owner %></td>
        <td><%= link_to 'Show', dealership %></td>
        <td><%= link_to 'Edit', edit_dealership_path(dealership) %></td>
        <td><%= link_to 'Destroy', dealership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dealership', new_dealership_path %>

BMacmillan/Labs/car_listings/app/views/dealerships/new.html.erb
<h1>New Dealership</h1>

<%= render 'form', dealership: @dealership %>

<%= link_to 'Back', dealerships_path %>

BMacmillan/Labs/car_listings/app/views/dealerships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dealership.name %>
</p>

<p>
  <strong>Location address:</strong>
  <%= @dealership.location_address %>
</p>

<p>
  <strong>Location city:</strong>
  <%= @dealership.location_city %>
</p>

<p>
  <strong>Location state:</strong>
  <%= @dealership.location_state %>
</p>

<p>
  <strong>Location zip:</strong>
  <%= @dealership.location_zip %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @dealership.owner %>
</p>

<%= link_to 'Edit', edit_dealership_path(@dealership) %> |
<%= link_to 'Back', dealerships_path %>