BMacmillan/Labs/car_listings/config/routes.rb
Rails.application.routes.draw do
  resources :prospects
  resources :salesmen
  resources :dealerships
  resources :car_infos
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

BMacmillan/Labs/car_listings/app/models/prospect.rb
class Prospect < ApplicationRecord
end

BMacmillan/Labs/car_listings/app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  before_action :set_prospect, only: [:show, :edit, :update, :destroy]

  # GET /prospects
  # GET /prospects.json
  def index
    @prospects = Prospect.all
  end

  # GET /prospects/1
  # GET /prospects/1.json
  def show
  end

  # GET /prospects/new
  def new
    @prospect = Prospect.new
  end

  # GET /prospects/1/edit
  def edit
  end

  # POST /prospects
  # POST /prospects.json
  def create
    @prospect = Prospect.new(prospect_params)

    respond_to do |format|
      if @prospect.save
        format.html { redirect_to @prospect, notice: 'Prospect was successfully created.' }
        format.json { render :show, status: :created, location: @prospect }
      else
        format.html { render :new }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prospects/1
  # PATCH/PUT /prospects/1.json
  def update
    respond_to do |format|
      if @prospect.update(prospect_params)
        format.html { redirect_to @prospect, notice: 'Prospect was successfully updated.' }
        format.json { render :show, status: :ok, location: @prospect }
      else
        format.html { render :edit }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospects/1
  # DELETE /prospects/1.json
  def destroy
    @prospect.destroy
    respond_to do |format|
      format.html { redirect_to prospects_url, notice: 'Prospect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospect
      @prospect = Prospect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prospect_params
      params.require(:prospect).permit(:first_name, :last_name, :email_Address, :location_address, :location_city, :location_state, :location_zip, :mobile_phone_number)
    end
end

BMacmillan/Labs/car_listings/app/helpers/prospects_helper.rb
module ProspectsHelper
end

BMacmillan/Labs/car_listings/app/views/prospects/_form.html.erb
<%= form_for(prospect) do |f| %>
  <% if prospect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prospect.errors.count, "error") %> prohibited this prospect from being saved:</h2>

      <ul>
      <% prospect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email_Address %>
    <%= f.text_field :email_Address %>
  </div>

  <div class="field">
    <%= f.label :location_address %>
    <%= f.text_field :location_address %>
  </div>

  <div class="field">
    <%= f.label :location_city %>
    <%= f.text_field :location_city %>
  </div>

  <div class="field">
    <%= f.label :location_state %>
    <%= f.text_field :location_state %>
  </div>

  <div class="field">
    <%= f.label :location_zip %>
    <%= f.text_field :location_zip %>
  </div>

  <div class="field">
    <%= f.label :mobile_phone_number %>
    <%= f.text_field :mobile_phone_number %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

BMacmillan/Labs/car_listings/app/views/prospects/edit.html.erb
<h1>Editing Prospect</h1>

<%= render 'form', prospect: @prospect %>

<%= link_to 'Show', @prospect %> |
<%= link_to 'Back', prospects_path %>

BMacmillan/Labs/car_listings/app/views/prospects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prospects</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email address</th>
      <th>Location address</th>
      <th>Location city</th>
      <th>Location state</th>
      <th>Location zip</th>
      <th>Mobile phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prospects.each do |prospect| %>
      <tr>
        <td><%= prospect.first_name %></td>
        <td><%= prospect.last_name %></td>
        <td><%= prospect.email_Address %></td>
        <td><%= prospect.location_address %></td>
        <td><%= prospect.location_city %></td>
        <td><%= prospect.location_state %></td>
        <td><%= prospect.location_zip %></td>
        <td><%= prospect.mobile_phone_number %></td>
        <td><%= link_to 'Show', prospect %></td>
        <td><%= link_to 'Edit', edit_prospect_path(prospect) %></td>
        <td><%= link_to 'Destroy', prospect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prospect', new_prospect_path %>

BMacmillan/Labs/car_listings/app/views/prospects/new.html.erb
<h1>New Prospect</h1>

<%= render 'form', prospect: @prospect %>

<%= link_to 'Back', prospects_path %>

BMacmillan/Labs/car_listings/app/views/prospects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @prospect.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @prospect.last_name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @prospect.email_Address %>
</p>

<p>
  <strong>Location address:</strong>
  <%= @prospect.location_address %>
</p>

<p>
  <strong>Location city:</strong>
  <%= @prospect.location_city %>
</p>

<p>
  <strong>Location state:</strong>
  <%= @prospect.location_state %>
</p>

<p>
  <strong>Location zip:</strong>
  <%= @prospect.location_zip %>
</p>

<p>
  <strong>Mobile phone number:</strong>
  <%= @prospect.mobile_phone_number %>
</p>

<%= link_to 'Edit', edit_prospect_path(@prospect) %> |
<%= link_to 'Back', prospects_path %>